### ISSUE TITLE
Is this excellent build still maintained?

### ISSUE THREAD

**Issue by Pharaoh2k** [Kpoodle/kpoodle.github.io#1]
And is there any forum or group for discussion?

**Comment by barronen1** [comment]
@PoodleStreaming
telegram

**Comment by TwillightMercy** [comment]
> > @PoodleStreaming telegram
> 
> Thanks

You wanted Kodi 20.0 + hebrew RTL subtitles
http://bit.ly/kodi7rd

**Comment by Pharaoh2k** [comment]
[**@TwillightMercy**](https://github.com/TwillightMercy) commented on [Feb 8, 2023, 1:27 PM GMT+7](https://github.com/Kpoodle/kpoodle.github.io/issues/1#issuecomment-1422081790 "2023-02-08T06:27:49Z - Replied by Github Reply Comments"):
> > > @PoodleStreaming telegram
> > 
> > Thanks
> 
> You wanted Kodi 20.0 + hebrew RTL subtitles
> http://bit.ly/kodi7rd
> 
> _Originally posted by @TwillightMercy in https://github.com/Kpoodle/kpoodle.github.io/issues/1#issuecomment-1422081790_

Thanks. They don't seem to have it available yet tho.
